### ISSUE TITLE
has_serial_no should be captured while creating bulk variants

### ISSUE THREAD

**Issue by vwithv1602** [vwithv1602git1/erpnext_old_prod#2]
There should be a field **has_serial_no** along with variant attributes(like Ram, HDD, Processor etc.,) while creating bulk variants.

> https://github.com/vwithv1602git1/erpnext_old_prod/commit/e2bcb0b4dd57a9cb0eb97643ac35afd7cf843d2f

**Comment by vwithv1602git1** [comment]
Fixed: https://github.com/vwithv1602git1/erpnext_old_prod/commit/1db81c60c40cb644770c31ae0b85314649b52756
