### ISSUE TITLE
Exclude return items in 'Delivered Items To Be Billed'

### ISSUE THREAD

**Issue by vwithv1602** [vwithv1602git1/erpnext_old_prod#6]
In 'Delivered Items To Be Billed', records which are returned should not be included.

**Comment by vwithv1602** [comment]
For Reference: (Hangout: 13012018 13:52)
**Requirement from Vishesh on 13012018**
> 3. There is a report call "Delivered but not billed" that shld ideally give delivered goods that we have not billed..
> but problem in this report is if there is a return delivery not it is still considering it as delivered.
> may be we can tweak that report itself or create a new one.

**Comment by vwithv1602git1** [comment]
https://github.com/vwithv1602git1/erpnext_old_prod/commit/a980d1470f4cfadd063e3ebe5bf84a01a6554261
